#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

cd /home/"${BASE_USER}"

apt-get install -y \
	git \
	rustc libssl-dev musl-dev musl-dev python3-dev libffi-dev pkg-config \
	python3 python3-pip python3-setuptools
	

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > get_rustup.sh
# sudo -u pi sh ./get_rustup.sh --profile minimal -y

# set up venv
#sudo -u pi python3 -m virtualenv -p python3 labgrid-venv
# . labgrid-venv/bin/activate
sudo -u pi git clone https://github.com/labgrid-project/labgrid
sudo -u pi pip install --upgrade pip
time sudo -u pi pip install ./labgrid

# Unpack root at the end, so files are modified before
unpack /filesystem/root /
